### PR TITLE
Use utcnow() when sending zulu time

### PR DESCRIPTION
**Pull request by benmurden**

### CODE REVIEW

**Comment by pp-randy** [comment]
Start_date is truncated to midnight of the merchant account time zone, so I think the sample needs to be updated to be for tomorrow, or plus one day.  Setup_fee ideally should be used for same day initial payments.

**Comment by jaypatel512** [comment]
Closing this PR as we do not need a UTC time here. It should be a future time based on merchant's account time zone. Samples can be updated to add 1 day to be safe/generic for all timezones, but it is solely for demonstration purpose.

**Comment by benmurden** [comment]
Is it correct to assume that the PayPal servers ignore the Z in the sent time stamp, and that they're always assumed to be of the merchant's time zone? If not, I think there's a possibility of accidentally sending a past date or further than intended future date.

Forgive me, but I don't see an explanation for this in the docs, so I presumed the sent time zone was honored.

**Comment by pp-randy** [comment]
You are correct @benmurden. I have a request open for documentation improvement / clarifications here https://github.com/paypal/PayPal-REST-API-issues/issues/68

**Pull request closed without merging**
