### PR TITLE
Implement inactivate method for billing plan

### PR DESCRIPTION
**Pull request by skudriashev**

### CODE REVIEW

**Comment by skudriashev** [comment]
@bluk could you please review this?)

**Comment by skudriashev** [comment]
@bluk for instance you have created 10 billing plans and some of them you don't need anymore. By this option you can inactivate some of them and work with active only. This is library is SDK and API allows this - I think we should cover this possibility. Thanks)

**Comment by skudriashev** [comment]
@bluk that's clear) Thanks!

**Comment by skudriashev** [comment]
@bluk can you merge please?

**Comment by bluk** [comment]
Thanks @skudriashev for the PR.

**Pull request merged**
