### PR TITLE
Build clean-up

### PR DESCRIPTION
**Pull request by skudriashev**
- Drop support of deprecated Python 2.6
- Drop support of EOL Python 3.3
- Add support of Python 3.5/3.6
- Create test-requirements.txt for test requirements

### CODE REVIEW

**Comment by hugovk** [comment]
Also remove `older_than_27()` and simplify where it was used. 

You could also drop Python 3.3, it's also EOL and little used.

Here's the pip installs for paypalrestsdk from PyPI for last month:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   77.5% |         12,480 |
| 3.6            |   14.2% |          2,284 |
| 3.5            |    5.1% |            814 |
| 3.4            |    3.2% |            511 |
| 3.3            |    0.0% |              8 |
| 3.7            |    0.0% |              1 |

Source: `pypinfo --start-date -60 --end-date -30 --percent --pip --markdown paypalrestsdk pyversion`

**Comment by skudriashev** [comment]
@hugovk updated :smiley:

**Comment by hugovk** [comment]
👍 

These can go:

https://github.com/paypal/PayPal-Python-SDK/blob/eed15dd7f03cbf091014c1a4c3aff76f4ef554ec/paypalrestsdk/util.py#L53-L55

https://github.com/paypal/PayPal-Python-SDK/blob/b376dc78579819cd9566aae2c3a8de9c9026cbfb/paypalrestsdk/api.py#L22-L23

**Comment by skudriashev** [comment]
@hugovk good catch))

**Comment by skudriashev** [comment]
@bluk hey, can you merge this please?

**Comment by skudriashev** [comment]
Can someone merge this, please?

**Comment by Alir3z4** [comment]
Your pull request has been limited, please resolve any open case or contact us :D

Anyway, anyone gonna merge this ?

**Comment by skudriashev** [comment]
I'm waiting it to be merged also ;(

**Pull request closed without merging**
